name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run build
      - name: Github Action for Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
